export const GET_PROJECTS_REQUESTED = "GET_PROJECTS_REQUESTED"
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS"
export const GET_PROJECTS_FAILED = "GET_PROJECTS_FAILED"

export const GET_PROJECT_REQUESTED = "GET_PROJECT_REQUESTED"
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS"
export const GET_PROJECT_FAILED = "GET_PROJECT_FAILED"

export const DELETE_PROJECT_REQUESTED = "DELETE_PROJECT_REQUESTED"
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS"
export const DELETE_PROJECT_FAILED = "DELETE_PROJECT_FAILED"

export const UPDATE_PROJECT_REQUESTED = "UPDATE_PROJECT_REQUESTED"
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS"
export const UPDATE_PROJECT_FAILED = "UPDATE_PROJECT_FAILED"

export const CREATE_PROJECT_REQUESTED = "CREATE_PROJECT_REQUESTED"
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS"
export const CREATE_PROJECT_FAILED = "CREATE_PROJECT_FAILED"